# Job Radar configuration
#
# Defines the job searches performed on different job boards and platforms.
#
# Each search specifies:
#   - name: General search name used to identify the search.
#   - url: URL of the predefined search, including any platform-specific filters.
linkedin:
  - name: Data and ML engineer
    url: "https://www.linkedin.com/jobs/search-results/?currentJobId=4437171347&keywords=%28%22Machine%20Learning%20Engineer%22%20OR%20%22Data%20Engineer%22%29%20AND%20%28medical%20OR%20diagnostics%20OR%20healthcare%20OR%20biotech%20OR%20medtech%20OR%20imaging%20OR%20clinical%29&origin=JOB_SEARCH_PAGE_JOB_FILTER&referralSearchId=mcz3Tsd0MjJqBVH5ds0Mlg%3D%3D&geoId=100027885&distance=24.85484&f_TPR=r2592000&f_SAL=f_SA_id_227001%3A276001%2C277001%24f_SA_id_226001%3A273001%2C275001%2C272015"

  - name: R&D Engineer
    url: "https://www.linkedin.com/jobs/search-results/?currentJobId=4278050399&keywords=%28%22Systems%20Engineer%22%20OR%20%22Project%20Engineer%22%20OR%20%22R%26D%20Engineer%22%20OR%20%22Biomedical%20Engineer%22%20OR%20%22Product%20Engineer%22%29%20AND%20%28medical%20OR%20diagnostics%20OR%20healthcare%20OR%20biotech%20OR%20medtech%20OR%20imaging%20OR%20clinical%29&origin=JOB_SEARCH_PAGE_JOB_FILTER&referralSearchId=mpFBToM9rAm%2BzHTogKErWA%3D%3D&geoId=100027885&distance=24.85484&f_TPR=r2592000&f_SAL=f_SA_id_227001%3A276001%2C277001%24f_SA_id_226001%3A273001%2C272015"

jobs_ch:
  - name: Biomedical Engineer
    url: "https://www.jobs.ch/de/stellenangebote/?employment-grade-max=100&employment-grade-min=80&employment-type=5&location=z%C3%BCrich&position=3&publication-date=7&region=7&region=19&region=20&region=22&term=biomedical%20engineer"

  - name: Entwicklungsingenieur Medizintechnik
    url: "https://www.jobs.ch/de/stellenangebote/?employment-grade-max=100&employment-grade-min=80&employment-type=5&location=z%C3%BCrich&position=3&region=7&region=19&region=20&region=22&term=entwicklungsingenieur%20medizintechnik"

